### ISSUE TITLE
Support stack transformations

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-java#478]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

This is a feature supported in other language SDKs but missing from the Java SDK.

https://www.pulumi.com/docs/intro/concepts/resources/options/transformations/#stack-transformations

**Comment by pawelprazak** [comment]
Unfortunately, setting transformations on the context is not possible with the current implementation of `Resource`.

Since `Stack` inherits `Resource` initialization logic, the transformations are registered in the constructor.
Also the `Stack` needs to exist **before** any user code is executed (including setting the transformations on the context).

Alternative APIs:

dotnet inspired (very easy to implement)
```
Pulumi.run(ctx -> { ... }, StackOptions.builder().transformations(...).build())
```
or a "fluent" approach (new public interface will be required for the `withStackTransformations` to have something to return
```
Pulumi
    .withStackTransformations(...)
    .run(ctx -> {...}
```

I personally don't have strong preference.
