### ISSUE TITLE
the java generator is generating bad maven coordinates in gradle

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi-java#627]
### What happened?

A customer reported:

> Haven’t dug too much into this yet but the java generator is generating bad maven coordinates in gradle:
>
>   implementation("com.pulumi:pulumi:v0.2.1")

### Steps to reproduce

wip

### Expected Behavior

valid maven coordinate in gradle

### Actual Behavior

INVALID maven coordinate in gradle

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pawelprazak** [comment]
Thank you for the report. I'm trying to reproduce.

running `pulumi new java-gradle` gives me this in `app/build.gradle`
```
dependencies {
    implementation 'com.pulumi:pulumi:(,1.0]'
}
```
and it makes sense, since it is using `templates/java-gradle/app/build.gradle`

It appears that the bug is localized to code using `pkg/codegen/java/build.gradle.template`
and the fix might be:
<img width="1092" alt="Screenshot 2022-05-25 at 10 48 23" src="https://user-images.githubusercontent.com/48874/170221896-26517ee7-39e1-4a52-a039-668aae862f62.png">

I'll try to find a way to reproduce this and test the patch against it.

**Comment by t0yv0** [comment]
Here is a repro.

Download 0.2.1 from GitHub releases.

Extract pulumi-java-gen from the release.

Generate some code:

```
pulumi-java-gen generate \
    --schema https://raw.githubusercontent.com/pulumi/pulumi-random/v4.6.0/provider/cmd/pulumi-resource-random/schema.json --out o --version 1.2.3
```

Observe 

```
$ cat o/build.gradle | grep 2.1                                                                    
implementation("com.pulumi:pulumi:v0.2.1")
```

Desired:

```
implementation("com.pulumi:pulumi:0.2.1")
```

**Comment by t0yv0** [comment]
This is coming from the feature where if not given `--sdk` it assumes it should link to an SDK that matches the version of `pulumi-java-gen` itself, but it must strip the v.

**Comment by t0yv0** [comment]
I'd like to see further testing, I don't believe the patch fixes it as it's off the affected code path. You need to generate a binary that responds with `v0.2.2` or similar to `version` not one that responds with `0.2.2` without a `v`, because that's what's happening in release builds (and seems correct, `pulumi version` also has a `v`).

**Comment by t0yv0** [comment]
Ah never mind, I tested and it works somehow.

**Comment by pawelprazak** [comment]
> pulumi version

From what I've observed, `pulumictl get version` is not returning `v` (at least the one I have):
```
$ pulumictl get version --tag-pattern '^pkg'
0.2.2-alpha.1653557926+6086b126
```
```
$ pulumictl version
0.0.31
```

To test the patch I've modified Makefile to add the `v` to see if the patch works and it worked.

Not sure when and why the `v` got dropped but unpatched main at the time of testing yday also worked correctly.

The merged patch will guard us against any changes in the future because it normalizes the input.

**Comment by pawelprazak** [comment]
Interestingly, when I go back to the commit tagged with `pkg/v0.2.1` the version from `pulumi-java-gen version`, I can't repro:
```
$ git status
HEAD detached at 024a09f7dfe
nothing to commit, working tree clean
$ make bin/pulumi-java-gen; bin/pulumi-java-gen version
make: `bin/pulumi-java-gen' is up to date.
0.2.1
```

There must be something special about the binary we release vs the binary we build locally.

I suspect the `goreleaser` change introduced at ab602d77:
```
  ldflags:
    - -X github.com/pulumi/pulumi-java/pkg/version.Version={{.Tag}}
```
It does not use `pulumictl`.

The `Makefile` uses:
```
	-ldflags "-X github.com/pulumi/pulumi-java/pkg/version.Version=$(shell pulumictl get version --tag-pattern '^pkg')" github.com/pulumi/pulumi-java/pkg/cmd/pulumi-java-gen
```

It looks like `gorelease` introduces at least one significant difference between what we test and what we release.
