### ISSUE TITLE
api too deep and complex, consider redesign

### ISSUE THREAD

**Issue by nagkumar** [pulumi/pulumi-java#809]
kubernetis api may be all other api of pulumi looks too complex,

![image](https://user-images.githubusercontent.com/332234/185129968-5a461291-ffb6-472e-8406-6e343fe59e69.png)

too much usage of build pattern, consider redesign, I expect this to be as close to yaml syntax way..

**Comment by lblackstone** [comment]
Hi @nagkumar, thanks for the comment. Since most of the Kubernetes APIs are deeply nested, it can be rather verbose in certain languages. That said, I don't expect that the Java SDK design will be changing from the established builder pattern.

You might consider trying one of our other SDKs like YAML or TypeScript, or you could use the [YAML SDKs](https://www.pulumi.com/registry/packages/kubernetes/api-docs/yaml/) to manage Kubernetes manifests directly.
